name: 'Pull Request to another repository'
description: 'Used to create a pull request to another repo with a package version update'
inputs:
  destination_repo:
    description: 'Destination repository'
    required: true
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination-repo }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-head-branch }}
    - ${{ inputs.destination-base-branch }}
branding:
  icon: 'git-commit'
  color: 'green'